### ISSUE TITLE
如何只针对特定的几类进行训练？

### ISSUE THREAD

**Issue by kypojk** [MVIG-SJTU/AlphAction#37]
你好，感谢你们的分享。
如题，我该如何像你们提供的实用模型一样，只针对一些常见类别进行训练呢？
期待你们的回复

**Comment by yelantf** [comment]
To do so , you need to sample the annotations files to keep only those target categories and then generate the json files following [DATA.md](../blob/master/DATA.md). And you should also rewrite the dataset class so that it will generate labels with those target classes. The related lines are as follows:
https://github.com/MVIG-SJTU/AlphAction/blob/99acc16d4fd91ddd91d34665ee9c21607ebbd9a0/alphaction/dataset/datasets/ava.py#L83-L90
https://github.com/MVIG-SJTU/AlphAction/blob/99acc16d4fd91ddd91d34665ee9c21607ebbd9a0/alphaction/dataset/datasets/ava.py#L166

Besides, in the config file, you should set `MODEL.ROI_ACTION_HEAD.NUM_CLASSES` to be the number of target categories and then set the right number for `MODEL.ROI_ACTION_HEAD.NUM_PERSON_MOVEMENT_CLASSE`, `MODEL.ROI_ACTION_HEAD.NUM_OBJECT_MANIPULATION_CLASSES`, `MODEL.ROI_ACTION_HEAD.NUM_PERSON_INTERACTION_CLASSES`. The sum of these three kinds of categories should match with the total number specified by `MODEL.ROI_ACTION_HEAD.NUM_CLASSES`. 

This is a little bit tricky and not supported by current codebase. But if you are familiar with PyTorch and python coding, it should not be too hard to implement it. Good luck with it.

**Comment by yelantf** [comment]
I believe I have answered your question, so I will close this issue now.
